// Question Document Schema
const mongoose = require('mongoose') // how importing kinda works with node.js
const Schema = mongoose.Schema


//Two things either we add email as field switch asked_by to a user
//or we add a question answer comment list to user so we can keep track of reputation
const QuestionSchema = new Schema({
    title: {type:String, required: true, maxLength: 50},
    summary: {type:String, required: true, maxLength: 140},
    text: {type: String, required: true},
    tags: [{type: Schema.Types.ObjectId, ref : 'Tag'}],
    answers: [{type: Schema.Types.ObjectId, ref : 'Answer'}],
    comments: [{type: Schema.Types.ObjectId, ref: 'Comment'}],
    asked_by: {type: String, default: "Anonymous"},
    userEmail: {type : String, required: true},
    ask_date_time: {type:Date, default: Date.now },
    views: {type: Number, default: 0},
    up_votes: {type: Number, default: 0}
}
);
//I think the _id is generated by mongo when a document is inserted into a collection
QuestionSchema.virtual('url').get(function(){
    return 'posts/question/' + this._id;
});
//NOTE that right now the schema is storing the object ids for tags and answers 
//we might have to switch so that it stores the actual objects themselves

module.exports = mongoose.model('Question',QuestionSchema);